// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBndtEgIxVKDCPuFeqDXLqbHhTqbl2ypfU',
    appId: '1:355880755380:web:2b5f38711fe2c15859f7e1',
    messagingSenderId: '355880755380',
    projectId: 'codenetra-ai',
    authDomain: 'codenetra-ai.firebaseapp.com',
    storageBucket: 'codenetra-ai.firebasestorage.app',
    measurementId: 'G-4HHBP8FTES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAgqXtQigdhtVUTHKWruVnZm_q6UMxF6Q',
    appId: '1:355880755380:android:54e2d6c30a391d8759f7e1',
    messagingSenderId: '355880755380',
    projectId: 'codenetra-ai',
    storageBucket: 'codenetra-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCamTVeQHv1ZqOZwda1bYvO-0neNGvA7cs',
    appId: '1:355880755380:ios:0aaa98228708e56659f7e1',
    messagingSenderId: '355880755380',
    projectId: 'codenetra-ai',
    storageBucket: 'codenetra-ai.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCamTVeQHv1ZqOZwda1bYvO-0neNGvA7cs',
    appId: '1:355880755380:ios:0aaa98228708e56659f7e1',
    messagingSenderId: '355880755380',
    projectId: 'codenetra-ai',
    storageBucket: 'codenetra-ai.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBndtEgIxVKDCPuFeqDXLqbHhTqbl2ypfU',
    appId: '1:355880755380:web:fa5aee3b0ef7389859f7e1',
    messagingSenderId: '355880755380',
    projectId: 'codenetra-ai',
    authDomain: 'codenetra-ai.firebaseapp.com',
    storageBucket: 'codenetra-ai.firebasestorage.app',
    measurementId: 'G-C82433EDWK',
  );
}
